### ISSUE TITLE
그룹 CRUD 

### ISSUE THREAD

**Issue by sik2** [sik2/l-lms-v1#11]
## 작업내역
그룹 조회, 목록 조회
그룹 생성, 수정, 삭제 api 작업 진행

## TODO
- [x] 스터디 그룹 목록 조회 API 구현 (GET /api/v1/groups)
- [x] 스터디 그룹 단일 조회 API 구현 (GET /api/v1/groups/{id})
- [x] 스터디 그룹 생성 API 구현 (POST /api/v1/groups)
- [x] 스터디 그룹 수정 API 구현 (PATCH /api/v1/groups/{id})
- [x] 스터디 그룹 삭제 API 구현 (DELETE /api/v1/groups/{id})

## 특이사항 or 참고사항
- 로그인된 회원이 초대된 스터디 그룹 리스트를 조회하기 위해 GroupMemberRepository 생성
- 현재 Member 객체는 임시 객체로 사용 
- 실제 로그인된 유저 기반으로 작업이 이뤄지지 않았기 때문에 이후 Security 적용이 필요

**Comment by jayjhseo** [comment]
작업내역
feature/#11 브랜치 작업 진행
그룹 조회, 목록 조회
그룹 생성, 수정, 삭제 api 작업 진행

TODO

특이사항 or 참고사항
그룹 목록 조회시 로그인된 회원의 전체 스터디그룹 목록을 조회하는 기능을
토큰값을 생성하고 로그인된 회원의 정보를 불러올 수 있을때 다시 수정할 예정

로그인된 회원이 초대된 스터디 그룹 리스트를 조회하기 위해 GroupMemberRepository 생성
