### ISSUE TITLE
SSO 로그인 처리

### ISSUE THREAD

**Issue by sik2** [sik2/l-lms-v1#13]
## 작업내역
- 카카오톡 SSO 로그인

## TODO
- [x] SSO 개념 재정리
- [x] 카카오 SSO 정보 발급
- [x] 백엔드 로그인 처리 로직 추가
- [x] 프론트엔드 로그인 요청 추가
