### ISSUE TITLE
서비스 api 서버 배포

### ISSUE THREAD

**Issue by sik2** [sik2/l-lms-v1#23]
## 작업내역
- aws ec2 를 이용한 무중단 배포 

## TODO
- [x] 테라폼을 이용한 vpc ec2 서버 생성
- [x] 배포를 위한 ec2 설정 작업
- [x] 스프링부트 배포 환경 셋팅
- [x] 수동배포
